### ISSUE TITLE
Unexpected Exception: maximum recursion depth exceeded in cmp

### ISSUE THREAD

**Issue by jvgutierrez** [anthcourtney/ansible-role-cis-amazon-linux#1]
Using ansible==2.2.0.0 and the following playbook against Amazon Linux 2016.09:
```

---

- hosts: localhost
  connection: local
  gather_facts: true
  become: yes

  vars:
    cis_level_1_exclusions:
      - 1.3.1
      - 1.3.2
      - "1.8"
      - 5.4.4
      - 3.4.2
      - 3.4.3
      - 6.2.13
    cis_pass_max_days: 45
    cis_umask_default: 002

  roles:
    - anthcourtney.cis-amazon-linux
```

I get the following error on task 2.1.3:
```
TASK [anthcourtney.cis-amazon-linux : include] *********************************
included: /home/ec2-user/anthcourtney.cis-amazon-linux/tasks/level-1/2.1.3.yml for localhost
ERROR! Unexpected Exception: maximum recursion depth exceeded in cmp```

If I add the task 2.1.3 to the exclusion list then I have the same issue with task 2.1.4.

I've attached the full traceback
[error.log.txt](https://github.com/anthcourtney/ansible-role-cis-amazon-linux/files/575106/error.log.txt)
